//
// Created by Mathias Vatter on 07.08.24.
//

#pragma once

#include "LoweringNDArray.h"

class NDArrayCopyFunction {
public:
	/// only copies between same dimensions allowed
	NDArrayCopyFunction(NodeProgram* program, NodeReference* array, NodeReference* array_to_copy):
		array(array), array_to_copy(array_to_copy), program(program) {
		// check if array and array_to_copy are NodeArrayRef or NodeNDArrayRef
		if(array->get_node_type() != NodeType::ArrayRef && array->get_node_type() != NodeType::NDArrayRef) {
			auto error = CompileError(ErrorType::TypeError, "", "", array->tok);
			error.m_message = "First argument of copy function has to be an <array> or <nd-array> reference.";
			error.exit();
		}

		generate_bounds();
		generate_iterators(array);
		if(array->get_node_type() == NodeType::NDArrayRef) {
			generate_dims_params(array);
		}
		// if the original array an array ref -> new dims have to be generated by looking at the array to copy
		if(array_to_copy->get_node_type() == NodeType::NDArrayRef) {
			generate_dims_params(array_to_copy);
		}
		generate_func_params();
	}

	std::string generate_func_name() {
		std::string name = generate_array_string(array);
		name += "<-";
		name += generate_array_string(array_to_copy);
		name += "["+array->ty->get_element_type()->to_string()+"]";
		return name;
	}

	std::unique_ptr<NodeFunctionDefinition> generate_function_def() {
		// new Assignment Node
		// update names
		array->name = "original";
		array_to_copy->name = "to_copy";
		auto assignment = std::make_unique<NodeSingleAssignment>(
			add_indexes(array),
			add_indexes(array_to_copy),
			array->tok
		);
		auto body = std::make_unique<NodeBlock>(Token(), true);
		body->add_stmt(std::make_unique<NodeStatement>(std::move(assignment), array->tok));
		body->wrap_in_loop_nest(std::move(iterators), std::move(lower_bounds), std::move(upper_bounds));

		// desugar for loop
//		body->statements.back()->statement->desugar(program);

		return std::make_unique<NodeFunctionDefinition>(
			std::make_unique<NodeFunctionHeader>(
				generate_func_name(),
				std::move(func_params),
				array->tok
			),
			std::nullopt,
			false,
			std::move(body),
			array->tok
		);
	}

	std::unique_ptr<NodeFunctionCall> generate_function_call() {
		auto func_call = std::make_unique<NodeFunctionCall>(
			false,
			std::make_unique<NodeFunctionHeader>(
				generate_func_name(),
				std::make_unique<NodeParamList>(Token()),
				array->tok
			),
			array->tok
		);
		func_call->function->add_arg(remove_indexes(array));
		func_call->function->add_arg(remove_indexes(array_to_copy));
		for(auto &dim : dims_to_copy) {
			func_call->function->add_arg(dim->clone());
		}
		return func_call;
	}

	std::unique_ptr<NodeFunctionCall> generate_copy_function() {
		auto func_call = generate_function_call();
		// check if function with this type already exists
		if(program->function_lookup.find({func_call->function->name, (int)func_params->params.size()}) != program->function_lookup.end()) {
			return func_call;
		}
		// generate function definition
		auto node_function_def = generate_function_def();
		program->additional_function_definitions.push_back(std::move(node_function_def));
		// update function lookup so that the new function can be found
		program->update_function_lookup();
		return func_call;
	}

private:
	NodeProgram* program;
	NodeReference* array;
	NodeReference* array_to_copy;
	/// iterator variables for the loop nest
	std::vector<std::unique_ptr<NodeDataStructure>> iterators;
	/// holds the variables for the dimensions to copy
	std::vector<std::unique_ptr<NodeDataStructure>> dim_vars_to_copy;
	/// copying actuall numbers of dims for the args in function call
	std::vector<std::unique_ptr<NodeAST>> dims_to_copy;
	/// lower bounds for the iterators
	std::vector<std::unique_ptr<NodeAST>> lower_bounds;
	/// upper bounds for the iterators
	std::vector<std::unique_ptr<NodeAST>> upper_bounds;
	/// function parameters
	std::unique_ptr<NodeParamList> func_params;


	void generate_bounds() {
		// if normal array -> only one bound
		if(array->get_node_type() == NodeType::ArrayRef) {
			lower_bounds.push_back(std::make_unique<NodeInt>(0, array->tok));
			upper_bounds.push_back(static_cast<NodeArrayRef*>(array)->get_size());
		}
		if(array->get_node_type() == NodeType::NDArrayRef) {
			auto node_nd_array_ref = static_cast<NodeNDArrayRef *>(array);
			// holds all iterators per wildcard
			int count = 1;
			for (auto &idx : node_nd_array_ref->indexes->params) {
				if (idx->get_node_type() == NodeType::Wildcard) {
					auto node_upper_bound = std::make_unique<NodeVariableRef>(
						"original.SIZE_D" + std::to_string(count), array->tok);
//					node_upper_bound->kind = NodeReference::Compiler;
					node_upper_bound->data_type = DataType::Const;
					upper_bounds.push_back(std::move(node_upper_bound));
					lower_bounds.push_back(std::make_unique<NodeInt>(0, array->tok));
					count++;
				}
			}
		}
	}
	void generate_iterators(NodeReference* array_ref) {
		int iter_size = iterators.size();
		// if normal array -> only one _iter1
		if(array_ref->get_node_type() == NodeType::ArrayRef) {
			auto node_iterator = std::make_unique<NodeVariable>(std::nullopt, "_iter"+std::to_string(iter_size), TypeRegistry::Integer, DataType::Mutable, array_ref->tok);
			node_iterator->is_local = true;
			iterators.push_back(std::move(node_iterator));
		}
		if(array_ref->get_node_type() == NodeType::NDArrayRef) {
			auto node_nd_array_ref = static_cast<NodeNDArrayRef *>(array_ref);
			// holds all iterators per wildcard
			int count = iter_size;
			for (auto &idx : node_nd_array_ref->indexes->params) {
				if (idx->get_node_type() == NodeType::Wildcard) {
					auto node_iterator = std::make_unique<NodeVariable>(std::nullopt, "_iter" + std::to_string(count), TypeRegistry::Integer, DataType::Mutable, array_ref->tok);
					node_iterator->is_local = true;
					iterators.push_back(std::move(node_iterator));
					count++;
				}
			}
		}
	}
	void generate_dims_params(NodeReference* array_ref) {
		int dims_size = dim_vars_to_copy.size();
		// if normal array -> only one _iter1
		if(array_ref->get_node_type() == NodeType::ArrayRef) {
			auto node_dim = std::make_unique<NodeVariable>(std::nullopt, "dim"+std::to_string(dims_size), TypeRegistry::Integer, DataType::Mutable, array_ref->tok);
			dim_vars_to_copy.push_back(std::move(node_dim));
		}
		if(array_ref->get_node_type() == NodeType::NDArrayRef) {
			auto node_nd_array_ref = static_cast<NodeNDArrayRef *>(array_ref);
			// holds all iterators per wildcard
			int count = dims_size;
			for (auto &idx : node_nd_array_ref->indexes->params) {
				if (idx->get_node_type() != NodeType::Wildcard) {
					auto node_dim = std::make_unique<NodeVariable>(std::nullopt, "dim" + std::to_string(count), TypeRegistry::Integer, DataType::Mutable, array_ref->tok);
					dim_vars_to_copy.push_back(std::move(node_dim));
					dims_to_copy.push_back(idx->clone());
					count++;
				}
			}
		}
	}

	void generate_func_params() {
		func_params = std::make_unique<NodeParamList>(array->tok);
		auto node_ndarray = std::make_unique<NodeNDArray>(
			std::nullopt,
			"ndarray",
			nullptr,
			nullptr, array->tok);
		auto node_array = std::make_unique<NodeArray>(
			std::nullopt,
			"array",
			nullptr,
			nullptr, array->tok);
		if(array->get_node_type() == NodeType::ArrayRef) {
			node_array->ty = array->ty;
			node_array->name = "original";
			func_params->add_param(node_array->clone());
		} else if(array->get_node_type() == NodeType::NDArrayRef) {
			node_ndarray->ty = array->ty;
			node_ndarray->name = "original";
			func_params->add_param(node_ndarray->clone());
		}
		if(array_to_copy->get_node_type() == NodeType::ArrayRef) {
			node_array->ty = array_to_copy->ty;
			node_array->name = "to_copy";
			func_params->add_param(node_array->clone());
		} else if(array_to_copy->get_node_type() == NodeType::NDArrayRef) {
			node_ndarray->ty = array_to_copy->ty;
			node_ndarray->name = "to_copy";
			func_params->add_param(node_ndarray->clone());
		}
		for(auto &dim : dim_vars_to_copy) {
			func_params->add_param(dim->clone());
		}
	}

	/// iterators have to be generated first!
	std::unique_ptr<NodeReference> add_indexes(NodeReference* array_ref) {
		auto indexes = std::make_unique<NodeParamList>(array_ref->tok);
		if(array_ref->get_node_type() == NodeType::ArrayRef) {
			auto node_array_ref = clone_as<NodeArrayRef>(array_ref);
			indexes->add_param(iterators[0]->to_reference());
			node_array_ref->index = std::move(indexes);
			node_array_ref->index->parent = node_array_ref.get();
			return node_array_ref;
		} else if(array_ref->get_node_type() == NodeType::NDArrayRef) {
			auto node_nd_array_ref = clone_as<NodeNDArrayRef>(array_ref);
			// holds all iterators per wildcard
			int count1 = 0; int count2 = 0;
			for (auto &idx : node_nd_array_ref->indexes->params) {
				if (idx->get_node_type() == NodeType::Wildcard) {
					indexes->add_param(iterators[count1]->to_reference());
					count1++;
				} else {
					indexes->add_param(dim_vars_to_copy[count2]->to_reference());
					count2++;
				}
			}
			node_nd_array_ref->indexes = std::move(indexes);
			node_nd_array_ref->indexes->parent = node_nd_array_ref.get();
			node_nd_array_ref->sizes = nullptr;
			return node_nd_array_ref;
		}
		return nullptr;
	}

	static std::unique_ptr<NodeReference> remove_indexes(NodeReference* array_ref) {
		if(array_ref->get_node_type() == NodeType::ArrayRef) {
			auto node_array_ref = clone_as<NodeArrayRef>(array_ref);
			node_array_ref->index = nullptr;
			return node_array_ref;
		} else if(array_ref->get_node_type() == NodeType::NDArrayRef) {
			auto node_nd_array_ref = clone_as<NodeNDArrayRef>(array_ref);
			node_nd_array_ref->indexes = nullptr;
			return node_nd_array_ref;
		}
		return nullptr;
	}

	/// ndarray[*, *] -> ndarray$dim2$2$3
	/// ndarray[1, *, *] -> ndarray$dim3$2$3
	static std::string generate_array_string(NodeReference* ref) {
		std::string name;
		if(ref->get_node_type() == NodeType::ArrayRef) {
			name += "array";
		}
		if(ref->get_node_type() == NodeType::NDArrayRef) {
			name += "ndarray";
			auto ndarray = static_cast<NodeNDArrayRef*>(ref);
			// add dimension size
			name += "$dim"+std::to_string(ndarray->indexes->size());
			for(int i=1; i<ndarray->indexes->params.size(); i++) {
				if(ndarray->indexes->params[i]->get_node_type() == NodeType::Wildcard) {
					name += "$"+std::to_string(i);
				}
			}
		}
		return name;
	}
};