name: Build and Deploy CKSP Compiler

on:
  push:
    # tags:
    #   - 'v*' # Trigger nur bei neuen Tags, z. B. v1.0.0
    branches:
      - master # Trigger bei Push auf main-Branch

jobs:
  build-macos:
    runs-on: macos-latest
    outputs:
      version_dir: ${{ steps.extract-version-macos.outputs.version_dir }}
      tag: ${{ steps.extract-tag-macos.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'

      - name: Install dependencies
        run: brew install ninja || echo "Ninja is already installed"

      - name: Install Rosetta
        run: |
          sudo softwareupdate --install-rosetta --agree-to-license || echo "Rosetta already installed"

      - name: Build CKSP for ARM64 (native)
        run: |
          export CI=true
          chmod +x build.sh
          chmod +x build_and_package.sh
          ./build_and_package.sh

      - name: Build CKSP for x86_64 (Rosetta)
        run: |
          export CI=true
          export ARCH_OVERRIDE=x86_64
          chmod +x build.sh
          chmod +x build_and_package.sh
          arch -x86_64 ./build_and_package.sh

      - name: Verify architectures of macOS binaries
        run: |
          file _Releases/*/macos_*/cksp

      - name: Extract version directory (macOS)
        id: extract-version-macos
        run: |
            chmod +x scripts/extract_version_dir.sh
            VERSION_DIR=$(./scripts/extract_version_dir.sh)
            echo "version_dir=$VERSION_DIR" >> $GITHUB_OUTPUT
            echo "Detected VERSION_DIR: $VERSION_DIR"
            ls _Releases/

      - name: Extract version and set tag
        id: extract-tag-macos
        run: |
            VERSION=$(cmake-build-release/cksp --version | awk '{print $3}')
            TAG="v${VERSION}"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "Detected TAG: $TAG"

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: _Releases/${{ steps.extract-version-macos.outputs.version_dir }} # Release-Dateien für macOS hochladen

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and install dependencies
        shell: pwsh
        run: |
          choco upgrade chocolatey
      
          if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
            choco install cmake --version=3.27.0 --force
          } else {
            Write-Host "CMake already installed"
            cmake --version
          }
      
          if (-not (Get-Command ninja -ErrorAction SilentlyContinue)) {
            choco install ninja
          } else {
            Write-Host "Ninja already installed"
            ninja --version
          }

      - name: Build CKSP (Windows)
        run: |
            cmd /c build_script.bat

      - name: Extract version directory (Windows)
        id: extract-version-windows
        shell: cmd
        run: |
            for /f "delims=" %%a in ('call scripts\extract_version_dir.bat') do echo VERSION_DIR=%%a >> %GITHUB_ENV%
            
            rem Ausgabe der extrahierten VERSION_DIR
            echo Extracted VERSION_DIR:
            for /f "delims=" %%a in ('call scripts\extract_version_dir.bat') do echo %%a
            
            rem Anzeigen des Inhalts des _Releases-Ordners
            echo Current _Releases folder content:
            dir _Releases /s
    

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: _Releases/${{ env.VERSION_DIR }} # Release-Dateien für Windows hochladen

  deploy:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if VERSION_DIR is set
        if: ${{ needs.build-macos.outputs.version_dir == '' || needs.build-macos.outputs.version_dir == null }}
        run: |
          echo "Error: VERSION_DIR is not set. Aborting workflow."
          exit 1

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: macos-release/

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: windows-release/

      - name: Merge artifacts into _Releases
        run: |
            ls windows-release/
            ls macos-release/
            # Sicherstellen, dass der Zielordner existiert
            mkdir -p _Releases/${{ needs.build-macos.outputs.version_dir }}
            
            # Dateien aus macos-release/ kopieren
            rsync -a macos-release/ _Releases/${{ needs.build-macos.outputs.version_dir }}/
            
            # Dateien aus windows-release/ kopieren
            rsync -a windows-release/ _Releases/${{ needs.build-macos.outputs.version_dir }}/

      - name: Fix permissions for macOS binary
        run: |
            find _Releases/${{ needs.build-macos.outputs.version_dir }} -type f ! -name "*.*" -exec chmod +x {} \;          

      - name: Push merged _Releases to master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add _Releases/${{ needs.build-macos.outputs.version_dir }}
            git commit -m "Merge artifacts for version ${{ needs.build-macos.outputs.version_dir }}"
            git push origin master

      - name: Delete existing Git tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git fetch --tags
            TAG="${{ needs.build-macos.outputs.tag }}"
      
            if git tag -l | grep -q "$TAG"; then
                git tag -d "$TAG"
                git push --delete origin "$TAG" || echo "Tag $TAG does not exist remotely, skipping deletion"
            else
                echo "Tag $TAG does not exist locally or remotely, skipping deletion"
            fi

      - name: Create and push Git tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git fetch --tags
            TAG="${{ needs.build-macos.outputs.tag }}"

            # Neuen Tag erstellen und pushen
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"

      # - name: Zip _Releases folder
      #   run: |
      #       zip -r _Releases/${{ needs.build-macos.outputs.version_dir }}.zip _Releases/${{ needs.build-macos.outputs.version_dir }} -x "*.DS_Store"
    
      - name: Zip version_dir folder
        run: |
            cd _Releases && zip -r ${{ needs.build-macos.outputs.version_dir }}.zip ${{ needs.build-macos.outputs.version_dir }} -x "*.DS_Store"
          

      - name: Delete GitHub release if it exists
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            EXISTING_RELEASE=$(gh release view "${{ needs.build-macos.outputs.tag }}" --json url --jq .url || echo "")
            if [ -n "$EXISTING_RELEASE" ]; then
            echo "Deleting existing release ${{ needs.build-macos.outputs.tag }}"
            gh release delete "${{ needs.build-macos.outputs.tag }}" --yes
            fi
            
      - name: Create GitHub release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            IS_PRERELEASE="false"
            if [[ "${{ needs.build-macos.outputs.tag }}" == *-* ]]; then
            IS_PRERELEASE="true"
            fi
            gh release create "${{ needs.build-macos.outputs.tag }}" \
            _Releases/${{ needs.build-macos.outputs.version_dir }}.zip \
            --title "Release ${{ needs.build-macos.outputs.tag }}" \
            --notes "Automatically generated release for ${{ needs.build-macos.outputs.tag }}" \
            --prerelease=$IS_PRERELEASE
